---
# initalize Vyos firewall

- name: "initalizing Vyos firewall"
  vyos_config:
    lines:
      - set system time-zone Asia/Dubai
      - set system name-server 185.56.88.4
      - set system name-server 86.96.202.162
      - set system name-server 8.8.8.8
      - set interface ethernet eth1 address dhcp
      - set service dns forwarding system
      - set service dns forwarding listen-on eth1
      - set firewall state-policy established action accept
      - set firewall broadcast-ping disable
      - set firewall syn-cookies enable
      - set firewall source-validation disable
      - set firewall send-redirects enable
      - set firewall receive-redirects disable
      - set firewall ip-src-route disable
      - set firewall all-ping disable
      - set firewall name Inside2Outside default-action accept
      - set firewall name Outside2Inside default-action accept
      - set firewall name Outside2Router default-action drop
      - set firewall name Outside2Inside enable-default-log
      - set firewall name Outside2Router enable-default-log
      - set firewall group address-group mysql-address-ips
      - set firewall group address-group mssql-address-ips
      - set firewall group address-group rdp-address-ips
      - set firewall group address-group ssh-address-ips
      - set firewall group address-group sftp-address-ips
      - set firewall group address-group banned-ips
      - set firewall group address-group buzinessware-ips
      - set firewall group address-group buzinessware-ips address 86.96.202.162
      - set firewall group address-group buzinessware-ips address 185.56.88.5
      - set firewall group address-group buzinessware-ips address 185.56.88.2
      - set firewall group address-group dns-address-ips address 8.8.8.8
      - set firewall group address-group dns-address-ips address 1.1.1.1
      - set firewall group address-group dns-address-ips address 8.8.4.4
      - set firewall group address-group dns-address-ips address 185.56.88.4
      - set firewall group address-group dns-address-ips address 86.96.202.162
      - set firewall group port-group ssh-router-port
      - set firewall group port-group ssh-port-group
      - set firewall group port-group sftp-port-group
      - set firewall group port-group mysql-port-group
      - set firewall group port-group rdp-port-group
      - set firewall group port-group mssql-port-group 
      - set firewall group port-group denied-port-group
      - set firewall group port-group dns-port-group
      - set firewall group port-group ssh-router-port port 49227
      - set firewall group port-group mysql-port-group port 3306
      - set firewall group port-group denied-port-group port 123
      - set firewall group port-group denied-port-group port 445
      - set firewall group port-group denied-port-group port 53
      - set firewall group port-group mssql-port-group port 1434
      - set firewall group port-group dns-port-group port 53           
      - set firewall name Outside2Inside rule 100 action drop
      - set firewall name Outside2Inside rule 100 source group address-group banned-ips
      - set firewall name Outside2Inside rule 100 protocol all
      - set firewall name Outside2Inside rule 100 description "drop rule for banned ips"
      - set firewall name Outside2Inside rule 101 action drop
      - set firewall name Outside2Inside rule 101 protocol tcp
      - set firewall name Outside2Inside rule 101 destination group port-group denied-port-group
      - set firewall name Outside2Inside rule 101 description "drop rule denied ports"
      - set firewall name Outside2Inside rule 102 action accept
      - set firewall name Outside2Inside rule 102 protocol tcp_udp
      - set firewall name Outside2Inside rule 102 source group address-group dns-address-ips
      - set firewall name Outside2Inside rule 102 description "accept rule for dns"          
      - set firewall name Outside2Inside rule 900 action accept
      - set firewall name Outside2Inside rule 900 protocol tcp_udp
      - set firewall name Outside2Inside rule 900 source group address-group sftp-address-ips
      - set firewall name Outside2Inside rule 900 destination group port-group sftp-port-group
      - set firewall name Outside2Inside rule 900 description "sftp access allow rule"
      - set firewall name Outside2Inside rule 901 action drop
      - set firewall name Outside2Inside rule 901 protocol tcp_udp
      - set firewall name Outside2Inside rule 901 destination group port-group sftp-port-group
      - set firewall name Outside2Inside rule 901 description "sftp access drop rule"      
      - set firewall name Outside2Inside rule 800 action accept
      - set firewall name Outside2Inside rule 800 protocol tcp_udp
      - set firewall name Outside2Inside rule 800 source group address-group ssh-address-ips
      - set firewall name Outside2Inside rule 800 destination group port-group ssh-port-group
      - set firewall name Outside2Inside rule 800 description "ssh access allow rule"
      - set firewall name Outside2Inside rule 801 action drop
      - set firewall name Outside2Inside rule 801 protocol tcp_udp
      - set firewall name Outside2Inside rule 801 destination group port-group ssh-port-group
      - set firewall name Outside2Inside rule 801 description "ssh access drop rule"      
      - set firewall name Outside2Inside rule 810 action accept
      - set firewall name Outside2Inside rule 810 protocol tcp_udp
      - set firewall name Outside2Inside rule 810 source group address-group sftp-address-ips
      - set firewall name Outside2Inside rule 810 destination group port-group sftp-port-group
      - set firewall name Outside2Inside rule 810 description "sftp access allow rule"
      - set firewall name Outside2Inside rule 811 action drop
      - set firewall name Outside2Inside rule 811 protocol tcp_udp
      - set firewall name Outside2Inside rule 811 destination group port-group sftp-port-group
      - set firewall name Outside2Inside rule 811 description "sftp access drop rule"             
      - set firewall name Outside2Inside rule 820 action accept
      - set firewall name Outside2Inside rule 820 protocol tcp
      - set firewall name Outside2Inside rule 820 source group address-group mysql-address-ips
      - set firewall name Outside2Inside rule 820 destination group port-group mysql-port-group
      - set firewall name Outside2Inside rule 820 description "mysql access allow rule"
      - set firewall name Outside2Inside rule 821 action drop
      - set firewall name Outside2Inside rule 821 protocol tcp
      - set firewall name Outside2Inside rule 821 destination group port-group mysql-port-group
      - set firewall name Outside2Inside rule 821 description "mysql access drop rule" 
      - set firewall name Outside2Inside rule 830 action accept
      - set firewall name Outside2Inside rule 830 protocol tcp
      - set firewall name Outside2Inside rule 830 source group address-group mssql-address-ips
      - set firewall name Outside2Inside rule 830 destination group port-group mssql-port-group
      - set firewall name Outside2Inside rule 830 description "mssql access allow rule"
      - set firewall name Outside2Inside rule 831 action drop
      - set firewall name Outside2Inside rule 831 protocol tcp
      - set firewall name Outside2Inside rule 831 destination group port-group mssql-port-group
      - set firewall name Outside2Inside rule 831 description "mssql access drop rule"       
      - set firewall name Outside2Inside rule 840 action accept
      - set firewall name Outside2Inside rule 840 protocol tcp
      - set firewall name Outside2Inside rule 840 source group address-group rdp-address-ips
      - set firewall name Outside2Inside rule 840 destination group port-group rdp-port-group
      - set firewall name Outside2Inside rule 840 description "rdp access allow rule"
      - set firewall name Outside2Inside rule 841 action drop
      - set firewall name Outside2Inside rule 841 protocol tcp
      - set firewall name Outside2Inside rule 841 destination group port-group rdp-port-group
      - set firewall name Outside2Inside rule 841 description "rdp access drop rule"  
      - set firewall name Outside2Router rule 903 action accept
      - set firewall name Outside2Router rule 903 protocol icmp 
      - set firewall name Outside2Router rule 903 source group address-group buzinessware-ips
      - set firewall name Outside2Router rule 902 action accept
      - set firewall name Outside2Router rule 902 protocol tcp_udp
      - set firewall name Outside2Router rule 902 source group address-group dns-address-ips
      - set firewall name Outside2Router rule 902 description "dns to router accept rule"
      - set firewall name Outside2Router rule 901 action accept
      - set firewall name Outside2Router rule 901 protocol tcp_udp
      - set firewall name Outside2Router rule 901 destination group port-group dns-port-group
      - set firewall name Outside2Router rule 901 description "dns to router accept rule"
      - set firewall name Outside2Router rule 900 action accept
      - set firewall name Outside2Router rule 900 protocol tcp
      - set firewall name Outside2Router rule 900 destination group port-group ssh-group-router
      - set firewall name Outside2Router rule 900 source group address-group buzinessware-ips
      - set firewall name Outside2Router rule 900 description "ssh to router allow rule"
      - set interfaces ethernet eth0 firewall local name Outside2Router
      - set interfaces ethernet eth0 firewall in name Outside2Inside
      - set interfaces ethernet eth0 firewall out name Inside2Outside
