---
# initalize Vyos firewall

- name: "initalizing Vyos firewall"
  vyos_config:
    lines:
      - set system time-zone Asia/Dubai
      - set system name-server 185.56.88.4
      - set system name-server 86.96.202.162
      - set system name-server 8.8.8.8
      - set service dns forwarding system
      - set service dns forwarding listen-on eth1
      - set firewall state-policy established action accept
      - set firewall broadcast-ping disable
      - set firewall syn-cookies enable
      - set firewall source-validation disable
      - set firewall send-redirects enable
      - set firewall receive-redirects disable
      - set firewall ip-src-route disable
      - set firewall all-ping disable
      - set firewall name Inside2Outside default-action accept
      - set firewall name Outside2Inside default-action accept
      - set firewall name Outside2Router default-action accept
      - set firewall name Outside2Inside enable-default-log
      - set firewall name Outside2Router enable-default-log
      - set firewall group address-group mysql-address-ips
      - set firewall group address-group mssql-address-ips
      - set firewall group address-group rdp-address-ips
      - set firewall group address-group ssh-address-ips
      - set firewall group address-group sftp-address-ips
      - set firewall group address-group banned-ips
      - set firewall group address-group buzinessware-ips
      - set firewall group address-group buzinessware-ips address 86.96.202.162
      - set firewall group address-group buzinessware-ips address 185.56.88.5
      - set firewall group address-group buzinessware-ips address 185.56.88.2
      - set firewall group address-group dns-address-ips address 8.8.8.8
      - set firewall group address-group dns-address-ips address 1.1.1.1
      - set firewall group address-group dns-address-ips address 8.8.4.4
      - set firewall group address-group dns-address-ips address 185.56.88.4
      - set firewall group address-group dns-address-ips address 86.96.202.162
      - set firewall group port-group ssh-router-port
      - set firewall group port-group ssh-port-group
      - set firewall group port-group sftp-port-group
      - set firewall group port-group mysql-port-group
      - set firewall group port-group rdp-port-group
      - set firewall group port-group mssql-port-group 
      - set firewall group port-group denied-port-group
      - set firewall group port-group dns-port-group
      - set firewall group port-group ssh-router-port port 49227
      - set firewall group port-group mysql-port-group port 3306
      - set firewall group port-group denied-port-group port 123
      - set firewall group port-group denied-port-group port 445
      - set firewall group port-group denied-port-group port 53
      - set firewall group port-group mssql-port-group port 1434
      - set firewall group port-group dns-port-group port 53
      - set firewall name Outside2Router rule 903 action accept
      - set firewall name Outside2Router rule 903 protocol icmp 
      - set firewall name Outside2Router rule 903 source group address-group buzinessware-ips
      - set firewall name Outside2Router rule 902 action accept
      - set firewall name Outside2Router rule 902 protocol tcp_udp
      - set firewall name Outside2Router rule 902 source group address-group dns-address-ips
      - set firewall name Outside2Router rule 902 description "dns to router accept rule"
      - set firewall name Outside2Router rule 901 action accept
      - set firewall name Outside2Router rule 901 protocol tcp_udp
      - set firewall name Outside2Router rule 901 destination group port-group dns-port-group
      - set firewall name Outside2Router rule 901 description "dns to router accept rule"
      - set firewall name Outside2Router rule 900 action accept
      - set firewall name Outside2Router rule 900 protocol tcp
      - set firewall name Outside2Router rule 900 destination group port-group ssh-group-router
      - set firewall name Outside2Router rule 900 source group address-group buzinessware-ips
      - set firewall name Outside2Router rule 900 description "ssh to router allow rule"      
      - set interface ethernet eth1 address dhcp
    save: yes
