---
# configure IPSec VPN on Vyos firewall

- name: "setting up IPSec VPN"
  vyos_config:
    lines:
      - set vpn ipsec auto-update 40
      - set vpn ipsec esp-group ipsecesp compression 'disable'
      - set vpn ipsec esp-group ipsecesp compression 'disable'
      - set vpn ipsec esp-group ipsecesp lifetime '{{ vyos_ipsec_esp_lifetime | default("3600") }}'
      - set vpn ipsec esp-group ipsecesp mode 'tunnel'
      - set vpn ipsec esp-group ipsecesp pfs 'disable'
      - set vpn ipsec esp-group ipsecesp proposal 1 encryption '{{ vyos_ipsec_esp_encryption | default("aes256") }}'
      - set vpn ipsec esp-group ipsecesp proposal 1 hash '{{ vyos_ipsec_esp_hash | default("sha1") }}'
      - set vpn ipsec ike-group ipsecike ikev2-reauth 'no'
      - set vpn ipsec ike-group ipsecike key-exchange 'ikev1'
      - set vpn ipsec ike-group ipsecike lifetime '{{ vyos_ipsec_ike_lifetime | default("28800") }}'
      - set vpn ipsec ike-group ipsecike proposal 1 dh-group '{{ vyos_ipsec_ike_dhgroup | default("5") }}'
      - set vpn ipsec ike-group ipsecike proposal 1 encryption '{{ vyos_ipsec_ike_encryption | default("aes256") }}'
      - set vpn ipsec ike-group ipsecike proposal 1 hash '{{ vyos_ipsec_ike_hash | default("sha1") }}'
      - set vpn ipsec ipsec-interfaces interface 'eth0'
      - set vpn ipsec logging log-modes 'all'
      - set vpn ipsec nat-traversal 'disable'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} authentication mode 'pre-shared-secret'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} authentication pre-shared-secret {{ vyos_ipsec_secret }}
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} connection-type 'initiate'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} default-esp-group 'ipsecesp'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} ike-group 'ipsecike'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} ikev2-reauth 'inherit'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} local-address {{ vyos_ipsec_local_ip }}
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} tunnel {{ vyos_ipsec_tunnel }} allow-nat-networks 'disable'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} tunnel {{ vyos_ipsec_tunnel }} allow-public-networks 'disable'
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} tunnel {{ vyos_ipsec_tunnel }} local prefix {{ vyos_ipsec_local_prefix }}
      - set vpn ipsec site-to-site peer {{ vyos_ipsec_peer_ip }} tunnel {{ vyos_ipsec_tunnel }} remote prefix {{ vyos_ipsec_remote_prefix }}
    save: yes

