---
# tasks file for anoop.vyos

- name: "vyos fact gather"
  vyos_facts:
    gather_subset: config
    gather_network_resources: interfaces
  when: (vyos_cmd is defined) and (vyos_cmd == "fact")
  
- name: "vyos ping test to a host {{vyos_host}}"
  vyos_ping:
    dest: "{{ vyos_host }}"
  register: result
  when: (vyos_cmd is defined) and (vyos_cmd == "ping") and (vyos_host is defined)

- name: "debug"
  debug:
    var: result.rtt
  when: (result is succeeded) and (result.rtt is defined)

- name: "vyos interface change"
  vyos_interface:
   name: "{{ vyos_interface }}"
   description: "{{ vyos_interface_description }}"
  when: (vyos_cmd is defined) and (vyos_cmd == "interface") and (vyos_interface is defined)

- name: "running initilization script"
  include_tasks: init.yaml
  when: (vyos_cmd is defined) and (vyos_cmd == "init")

- name: "backup config from vyos host {{ inventory_hostname }}"  
  vyos_config:
    backup: yes
    backup_options:
      filename: backup-{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}.cfg
      dir_path: /{{ vyos_backup_path }}/{{inventory_hostname}}
  when: (vyos_cmd is defined) and (vyos_cmd == "backup") 
  
- name: "add {{ vyos_fw_ipaddress }} address in firewall address group {{ vyos_fw_address_group }}"  
  vyos_config:
    lines:
      - set firewall group address-group {{ vyos_fw_address_group }} address {{ vyos_fw_ipaddress }}
    save: yes
  when: (vyos_cmd is defined) and (vyos_cmd == "addip2fw") and (vyos_fw_address_group is defined) and (vyos_fw_address_group is defined)
  
- name: "delete {{ vyos_fw_ipaddress }} address in firewall address group {{ vyos_fw_address_group }}"  
  vyos_config:
    lines:
      - delete firewall group address-group {{ vyos_fw_address_group }} address {{ vyos_fw_ipaddress }}
    save: yes
  when: (vyos_cmd is defined) and (vyos_cmd == "delip2fw") and (vyos_fw_address_group is defined) and (vyos_fw_address_group is defined) 

- name: "add {{ vyos_fw_port }} port in firewall port group {{ vyos_fw_port_group }}"  
  vyos_config:
    lines:
      - set firewall group port-group {{ vyos_fw_port_group }} port {{ vyos_fw_port }}
  when: (vyos_cmd is defined) and (vyos_cmd == "addport2fw") and (vyos_fw_port_group is defined) and (vyos_fw_port is defined) 

- name: "delete {{ vyos_fw_port }} port in firewall port group {{ vyos_fw_port_group }}"  
  vyos_config:
    lines:
      - del firewall group port-group {{ vyos_fw_port_group }} port {{ vyos_fw_port }}
    save: yes
  when: (vyos_cmd is defined) and (vyos_cmd == "delport2fw") and (vyos_fw_port_group is defined) and (vyos_fw_port is defined) 

- name: "add new port group {{ vyos_fw_port_group }} in firewall with port {{ vyos_fw_port }}"  
  vyos_config:
    lines:
      - set firewall group port-group {{ vyos_fw_port_group }} port {{ vyos_fw_port }}
  when: (vyos_cmd is defined) and (vyos_cmd == "addnewport2fw") and (vyos_fw_port_group is defined) and (vyos_fw_port is defined)

- name: "add new address group {{ vyos_fw_address_group }} in firewall with port {{ vyos_fw_ipaddress }}"  
  vyos_config:
    lines:
      - set firewall group address-group {{ vyos_fw_address_group }} address {{ vyos_fw_ipaddress }}
    save: yes
  when: (vyos_cmd is defined) and (vyos_cmd == "addnewaddress2fw") and (vyos_fw_address_group is defined) and (vyos_fw_ipaddress is defined)
    
- name: "add new rule {{ vyos_fw_rule_number }} in firewall {{ vyos_fw_name }}"  
  vyos_config:
    lines:
      - set firewall name {{ vyos_fw_name }} rule {{ vyos_fw_rule_number }} action accept
      - set firewall name {{ vyos_fw_name }} rule {{ vyos_fw_rule_number }} protocol {{ vyos_fw_protocol }}
      - set firewall name {{ vyos_fw_name }} rule {{ vyos_fw_rule_number }} source group address-group {{ vyos_fw_address_group }}
      - set firewall name {{ vyos_fw_name }} rule {{ vyos_fw_rule_number }} destination group port-group {{ vyos_fw_port_group }}
      - set firewall name {{ vyos_fw_name }} rule {{ vyos_fw_rule_number }} description "accept rule"
    save: yes
  when: (vyos_cmd is defined) and (vyos_cmd == "addnewrule2fw") and (vyos_fw_port_group is defined) and (vyos_fw_address_group is defined) and (vyos_fw_rule_number is defined) and (vyos_fw_name is defined)
  
- name: "Setting up IPSec VPN Tunnel"
  include_tasks: ipsec.yaml
  when: (vyos_cmd is defined) and (vyos_cmd == "ipsecadd")
  
- name: "Delete up IPSec VPN Tunnel"
  include_tasks: ipsecdelete.yaml
  when: (vyos_cmd is defined) and (vyos_cmd == "ipsecadd")  