---
   
# generating server certificates        
- name: setfact 
  set_fact:
    ansible_connection: ssh
            
# gather hostname
- name: gethering hostname
  command: /bin/hostname
  register: _result

- name: setfact
  set_fact:
    openvpn_host: "{{_result.stdout}}"
    
# setting folder and files on the Vyos Router
- name: create client certificate
  shell: ./easyrsa --keysize=1024 build-client-full {{openvpn_client}} nopass
  args: 
    chdir: /config/auth/ovpn/
  ignore_errors: yes
  when: (openvpn_client is defined) and (vyos_cmd == "openvpn-client-add")
           
- name: create temp directory
  file:
    path: "/tmp/{{openvpn_host}}"
    state: directory
    mode: '0755'
  when: (vyos_cmd == "openvpn-client-add")
        
# create openvpn template
- name: create openvpn template
  template:
    src: templates/openvpn.j2
    dest: "{{openvpn_dest_folder}}/{{openvpn_host}}/{{openvpn_client}}.ovpn"
  when: (vyos_cmd == "openvpn-client-add")
    
- name: Sending an e-mail
  mail:
    host: smarthost.apps.ae
    port: 25
    username: mailuser
    password: X2avPBU9P97s
    to: "{{openvpn_client}} <{{openvpn_client_email}}>"
    subject: OpenSSL VPN User
    body: New User has been successfully created. Attached are the configuration files.
    subtype: html
    from: system@buzinessware.com
    attach:
      - "/config/auth/ovpn/pki/private/{{openvpn_client}}.key"
      - "/config/auth/ovpn/pki/issued/{{openvpn_client}}.crt"
      - "/config/auth/ovpn/pki/ca.crt"
      - "{{openvpn_dest_folder}}/{{openvpn_host}}/{{openvpn_client}}.ovpn"
  when: (vyos_cmd == "openvpn-client-add")
      
- name: deleting temp files
  file: 
    path: "{{openvpn_dest_folder}}/{{openvpn_host}}/{{openvpn_client}}.ovpn"
    state: absent
  when: (vyos_cmd == "openvpn-client-add")
  
- name: revoking user
  shell: "./easyrsa revoke {{openvpn_client}}"
  args: 
    chdir: /config/auth/ovpn/
  ignore_errors: yes
  when: (vyos_cmd == "openvpn-client-delete")
  
    